version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "SpecFlow"
      - match:
          dependency_name: "SpecFlow.*"